[DRIVER_SETTINGS]
ORA     U7.0
MSS     U4.0
SEQ	U1.0
usys$ora_params= open cursors 200,dpa,fv
usys$mss_params=gran=row,hs=on,oc=400,os=400,recsize=8000,step=10,checks=on,ents=lower,ids=quoted,iso=rc,locktime=-1,logtime=10,mapping=2,nls=off,pra=off,procs=on,ri=uniface

[SETTINGS]

; test for closing idf when finished
$PUTMESS_LOGFILE = D:\DBUpdate\MessagesGenerated_v2\Logs\%p_%u_putmess.TXT /append
$TRANSCRIPT_LOGFILE = D:\DBUpdate\MessagesGenerated_v2\Logs\%p_%u_transcript.TXT /append

[PATHS]
$MSS_REP = MSS:ALSQL2K8R2S01:Messages2xGenerated|ital|ital
$DEF = $MSS_REP
$IDF = $MSS_REP
$SYS = $MSS_REP
$UUU = $MSS_REP

[FILES]
*.txt = .\*.txt
*.xml = *.xml
*.cptlst=H:\*.pro
*.prt=H:\*.prt
*.txt=H:\*.txt
*.out=H:\*.out
*.imp=H:\*.imp
*.inf=H:\*.inf
*.if2=H:\*.if2
*.dot=H:\*.doc
*.pro=H:\*.pro
*.ora=H:\*.ora
*.exp=H:\*.exp
*.ins=H:\*.ins

[LOGICALS]
PRINT_SCRIPTS=NO

[WIDGETS]
bigbuttonfield=ucmdbutton(font=bigfont;tooltip=on;representation=UNIFACE)
buttonbarfield=wid_btnbar(font=buttons)
buttonfield=ucmdbutton(font=buttons;tooltip=on;representation=UNIFACE)
checkfield=wid_chkbox(font=label;3d=on)
combofield=ucombobox(font=editfont;3d=on;forcefit=on;frame=on;insert=unique;leftj=on)
dropdownfield=udropdownlist(font=buttonfont;forcefit=on;3D=on;Frame=on;dynamic=off)
dropdownwid=wid_drpdwn(font=editfont;dynamic=on)
spinfield=uspinbutton(font=editfont;autoselect=on)
editfield=wid_edtbox(font=editfont;3d=on;frame=off;autoselect=on;cursor=on;leftj=on;upper=1)
labelfield=wid_edtbox(font=label;3d=off;frame=off;autoselect=off;cursor=off;leftj=on)
smallfield=ueditbox(font=smallfont;3d=off;frame=off;autoselect=off;cursor=off;leftj=off;multiline=on)
picturefield=upicture(ToolTipText=on)
radiofield=uradiogroup(font=label)
scrollfield=wid_scroll
superfield=wid_superx
tabfield=utab(font=label)
treefield=utree(font=label)

[USER_3GL]
P:\CS08_3X\messages\BIN\cmdnet32.dll
P:\CS08_3X\messages\BIN\cmdutl32.dll
P:\CS08_3X\messages\BIN\cmdwid32.dll
P:\CS08_3X\messages\BIN\cmdout32.dll
P:\CS08_3X\messages\BIN\cmdtra32.dll
P:\CS08_3X\messages\BIN\cmdtrb32.dll
P:\CS08_3X\messages\BIN\cmdasy32.dll
P:\CS08_3X\messages\BIN\cmdvba32.dll
P:\CS08_3X\messages\BIN\hhctrl.ocx
P:\CS08_3X\messages\BIN\uauthlogin.dll

[SETTINGS]
$language=USA
$variation=USER
$enhanced_edit=all
$search_object=dbms_first
$search_descriptor=dbms_first
$no_valrep_check
$stop_on_div_by_zero=false
$search_resources=resources_first
$resources_output=D:\DBUpdate\MessagesGenerated_v2\resources 

[RESOURCES]
USYSUNIFACE:cmd_idf_resources\resources
USYS:usys.uar
USYS:uidf.uar
USYS:udbg.uar
D:\DBUpdate\MessagesGenerated_v2\resources

[ENTITIES]
*.sysenv usys:*.*


